version: '3.1'

services:
  mysql:
    image: mysql:5.7
    # image: mysql:8.0
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=oop_crud
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - "./import:/import:rw"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=secret --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10

  website:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - "./src:/var/www/html/:rw"
    ports:
      - 9000:80
    depends_on: 
      - mysql
    links:
      - mysql

